---
# These tasks install Apache web server

- name: Install Apache
  yum: name={{ item }} state=present
  with_items:
   - httpd

- name: Remove Apache default conf
  file: dest=/etc/httpd/conf.d/welcome.conf state=absent

- name: Create apache root landing page
  template: src=root_landingpage.html dest=/var/www/html/index.html owner=root group=root mode=644

- name: Whydah image
  copy: src=whydah.png dest=/var/www/html/whydah.png owner=root group=root mode=644


- name: Copy Apache config
  template: src=whydah.conf dest=/etc/httpd/conf.d/whydah.conf owner=root group=root mode=644

- name: restart apache
  service: name=httpd state=restarted enabled=yes