---
# This playbook deploys Whydah to AWS AMI's

- name: Set up Standard server configuration
  hosts:
    - Whydah_UserIdentityBackend
    - Whydah_SecurityTokenService
    - Whydah_SSOLoginWebApp
    - Whydah_UserAdminWebApp
    - Whydah_TestWebApp
    - Whydah_UserAdminService
  sudo: true
  roles:
    - standard
  tags:
    standard

- name: Set up Whydah UserIdentityBackend
  hosts: Whydah_UserIdentityBackend
  sudo: true
  roles:
    - configuration
    - file_transfer
    - app
  tags:
    uib
  vars:
    username: UserIdentityBackend
    group_id: net/whydah/identity
    app_name: UserIdentityBackend
    #env_mode: PROD
    #env_vars: -DIAM_MODE=PROD
    #service_config_template: useridentitybackend.properties
    #service_config: useridentitybackend.PROD.properties
    env_mode:
    env_vars: -DCONSTRETTO_TAGS=dev
    service_config_template: useridentitybackend.properties
    service_config: useridentitybackend_override.properties
    folders_to_copy: prodInitData
    #verify_service_url: http://localhost:9995/uib/authenticate/application/
  vars_files:
    - vars/uib
  tasks:
  - name: Add UIB specific libraries
    yum: name=openldap-clients state=present

- name: Create STS hazelcast file
  hosts: Whydah_SecurityTokenService
  sudo: true
  roles:
    - configuration
  tags:
    sts
  vars:
    username: SecurityTokenService
    service_config_template: hazelcast.xml
    service_config: hazelcast.xml

- name: Set up Whydah SecurityTokenService
  hosts: Whydah_SecurityTokenService
  sudo: true
  roles:
    - configuration
    - app
  tags:
    sts
  vars:
    username: SecurityTokenService
    group_id: net/whydah/token
    app_name: SecurityTokenService
    env_vars: -DIAM_MODE=PROD -Dhazelcast.config=hazelcast.xml -DIAM_CONFIG=/home/{{username}}/{{service_config}}
    service_config_template: securitytokenservice.properties
    service_config: securitytokenservice.PROD.properties
#    verify_service_url: http://localhost:9998/tokenservice/
  vars_files:
    - vars/securityTokenService

- name: Set up Whydah SSOLoginWebApp
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - configuration
    - app
  tags:
    sso
  vars:
    username: SSOLoginWebApp
    group_id: net/whydah/sso
    app_name: SSOLoginWebApp
    env_vars: -DIAM_MODE=PROD -DIAM_CONFIG=/home/{{username}}/{{service_config}}
    service_config_template: ssologinservice.properties
    service_config: ssologinservice.PROD.properties
    verify_service_url: http://localhost:9997/sso/login
  vars_files:
    - vars/ssoLogin

- name: Set up Whydah UserAdminWebApp
  hosts: Whydah_UserAdminWebApp
  sudo: true
  roles:
    - configuration
    - app
  tags:
    uawa
  vars:
    username: UserAdminWebApp
    group_id: net/whydah/identity
    app_name: UserAdminWebApp
    env_vars: -DIAM_MODE=PROD -DIAM_CONFIG=/home/{{username}}/{{service_config}}
    service_config_template: useradminwebapp.properties
    service_config: useradminwebapp.PROD.properties
    verify_service_url: http://localhost:9996/useradmin
  vars_files:
    - vars/userAdministration

- name: Set up Whydah UserAdminService
  hosts: Whydah_UserAdminService
  sudo: true
  roles:
    - configuration
    - app
  tags:
    uas
  vars:
    username: UserAdminService
    group_id: net/whydah/identity
    app_name: UserAdminService
    env_vars: -DIAM_MODE=PROD -DIAM_CONFIG=/home/{{username}}/{{service_config}}
    service_config_template: useradminservice.properties
    service_config: useradminservice.PROD.properties
    verify_service_url: http://localhost:9992/useradminservice/1/1/user/ping/pong
  vars_files:
    - vars/userAdminService

- name: Set up Whydah TestWebApp
  hosts: Whydah_TestWebApp
  sudo: true
  roles:
    - configuration
    - app
  tags:
    testapp
  vars:
    username: TestWebApp
    group_id: net/whydah/sso/web
    app_name: TestWebApp
    env_vars: -DIAM_MODE=TEST -DIAM_CONFIG=/home/{{username}}/{{service_config}}
    service_port: 9990
    service_config_template: testwebapp.properties
    service_config: testwebapp.TEST.properties
    verify_service_url: http://localhost:9990/test/hello
  vars_files:
    - vars/testwebapp

- name: Set up Apache config
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - apache
  tags:
    apache
