- name: Set up user
  user: name={{username}} shell="/bin/bash"

- name: Set up app config file
  template: src={{service_config_template}} dest=/home/{{username}}/{{service_config}} backup=true
  sudo_user: "{{username}}"
