---
- name: Disable requirement of tty to enable pipelining - If this step fails - temporarily set ansible.cfg pipelining = False
  lineinfile: dest=/etc/sudoers regexp="Defaults    requiretty" line="Defaults    !requiretty"

- name: Upgrade all packages
  yum: name=* state=latest

- name: Install standard linux utilities
  yum: name={{item}} state=present
  with_items:
  - telnet
  - lynx
  - wget
  - tree
  - java-1.8.0-openjdk


- name: Set server identifyer in bash
  lineinfile: dest=~/.bash_profile regexp="^export PS1=" line='export PS1="[\u@\h/{{deployment_identifyer}} \w]$"'
  sudo: false