---

- name: Set app version to fetch - {{version}}
  lineinfile: dest=/home/{{username}}/update-service.sh regexp="^V=" line='V={{version}}'
  sudo_user: "{{username}}"
  
- name: Fetch version {{version}} of app
  command: /home/{{username}}/update-service.sh chdir=/home/{{username}}
  sudo_user: "{{username}}"

# This step may fail if the service has been tampered with
- name: ReStart App service
  service: name="{{app_name}}" state=restarted
  ignore_errors: yes

#- name: ReStart App service
#  command: /home/ec2-user/restart-{{app_name}}.sh chdir=/home/ec2-user/


#### Test that service works:
- wait_for: port={{service_port}} delay=5 timeout=30

- name: Test that service responds
  get_url: url={{verify_service_url}} dest=/tmp/test_{{app_name}} force=true
  when: verify_service_url is defined
  register: result

- debug: msg="{{result}}"
